dist: bionic
# see https://docs.travis-ci.com/user/languages/python/
language: python
# python versions to be tested
python:
#  - "2.7" # see https://github.com/WolfgangFahl/gremlin-python-tutorial/issues/7
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
# allow gui output
#services:
#  - xvfb
before_install:
  # check version
  - lsb_release -a
install:
  - echo $USER
script:
# install apache jena and load example data
  - scripts/installAndTest
