#!/bin/bash
# create docs
# WF 2024-07-28 - updated

#
# check mkdocs is installed
#
if ! command -v mkdocs &> /dev/null
then
  pip install mkdocs mkdocs-material mkdocstrings[python]
fi
index_md=docs/index.md
if [ ! -f $index_md ]
then
cat << EOF > $index_md
# API Documentation

::: sidif
    options:
      show_submodules: true
EOF
fi

export PYTHONWARNINGS="ignore::DeprecationWarning"
mkdocs build
if [ "$1" = "deploy" ]
then
  mkdocs gh-deploy
fi
