#!/bin/bash
# WF 2020-06-03
# direct unit tests
python3 -m unittest discover
# test using the green tool
test_with_green() {
  pip list | egrep "^green "
  if [ $? -ne 0 ]
  then
    pip install green
  fi
  green tests -s 1
}
